# Generated by Django 5.1.6 on 2025-02-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleownership',
            name='status',
            field=models.CharField(choices=[('owned', 'Äger'), ('previously_owned', 'Har ägt')], default='owned', max_length=20),
        ),
    ]
