# Generated by Django 5.1.6 on 2025-02-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_add_owned_since'),
        ('puzzles', '0002_puzzleownership_status'),
    ]

    operations = [
    ]
