# Generated by Django 5.1.6 on 2025-02-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_merge_20250209_2343'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='puzzleownership',
            table='puzzles_puzzleownership',
        ),
    ]
